# Generated by Django 3.1.4 on 2021-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('function', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('img', models.FileField(upload_to='')),
                ('url1', models.URLField(null=True)),
                ('label1', models.TextField()),
                ('url2', models.URLField()),
                ('label2', models.TextField()),
            ],
        ),
    ]
