# Generated by Django 3.1.4 on 2021-07-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210705_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
