# Generated by Django 3.1.4 on 2021-07-06 16:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_boardmember_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('function', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='adminuploads'), upload_to='')),
                ('order', models.IntegerField(blank=True, default=1)),
                ('url1', models.URLField(blank=True)),
                ('label1', models.TextField(blank=True)),
                ('url2', models.URLField(blank=True)),
                ('label2', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='adminuploads'), upload_to=''),
        ),
    ]
