# Generated by Django 3.1.4 on 2021-07-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210706_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('heading', models.TextField(primary_key=True, serialize=False)),
                ('subheading', models.TextField()),
                ('btntext', models.TextField()),
                ('btnurl', models.TextField()),
            ],
        ),
    ]
