# Generated by Django 3.1.4 on 2021-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='mainproject',
            field=models.BooleanField(default=True),
        ),
    ]
