# Generated by Django 3.1.4 on 2021-07-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210708_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt',
            field=models.TextField(blank=True),
        ),
    ]
