# Generated by Django 3.1.7 on 2022-02-10 15:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_aanmeldingen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='creative',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='creative',
            name='img',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='adminuploads'), upload_to=''),
        ),
    ]
