# Generated by Django 3.1.7 on 2022-02-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220210_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='iframe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
