# Generated by Django 3.1.7 on 2022-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20220210_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meedoentekst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst1', models.TextField()),
                ('knop1_tekst', models.CharField(max_length=50)),
                ('knop1_url', models.CharField(max_length=50)),
                ('knop2_tekst', models.CharField(max_length=50)),
                ('knop2_url', models.CharField(max_length=50)),
                ('tekst2_kop', models.CharField(max_length=50)),
                ('tekst2', models.TextField()),
            ],
        ),
    ]
