# Generated by Django 3.1.7 on 2022-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_aanmeldingen_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aanmeldingen',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='aanmeldingen',
            name='repetitie_toelichting',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aanmeldingen',
            name='toelichting_instrument',
            field=models.TextField(blank=True),
        ),
    ]
